### ISSUE TITLE
branches missing

### ISSUE THREAD

**Issue by djpeach** [rockthejvm/scala-at-light-speed#1]
Hi there, tried to follow the first steps in checking out the start branch and the other branches are not there. The only branch is the master one. I see the zip files in the tags part, but would be nice if we could do it all through git.

**Comment by daniel-ciocirlan** [comment]
Does checking out tags work? You can branch very easily from there

**Comment by djpeach** [comment]
I will try this tmrw, as I’m not sure exactly what “checkout tags” means, I have never heard that before and can look into how to do that, but I can say that just running `checkout start` does NOT work as it is right now, but is what the README says to do

**Comment by djpeach** [comment]
`git checkout start` does work, just puts you in a detached state.
